### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nj4x** [shayhatsor/zookeeper#2]
Dear Shay,

I have a question about absence of await configuration in ZooKeeperNetEx implementation.
Could you please explain rationalities behind not using ConfigureAwait(false) ?
(seems I'm missing a point as long as I'm new to .Net dev)

**Comment by shayhatsor** [comment]
hi @nj4x,
I've just checked the entire codebase, you're right, I've missed `ConfigureAwait(false)` in a few places, mostly in the recipes. I guess its time to integrate some automated test for `ConfigureAwait(false)`. I know there's some Roslyn solutions, I'll try to see if these are mature enough.
I'll commit a fix and roll out a new release.
thanks for pointing this out!
shay

**Comment by nj4x** [comment]
Thanks!
