### ISSUE TITLE
where is "org.apache.zookeeper.data" and "org.apache.zookeeper.proto" ?

### ISSUE THREAD

**Issue by xuweixuwei** [shayhatsor/zookeeper#20]
i want to debug zookeeper ,i download  source(3.4.6.1006), open it in vs2017 , but cannot find "org.apache.zookeeper.data",and so on ,where is "org.apache.zookeeper.data" and "org.apache.zookeeper.proto"   ? thanks

**Comment by shayhatsor** [comment]
you should download the latest source. also, don't forget to run ant on the root folder of the project, it creates these files.
