### ISSUE TITLE
ZooKeeper.updateServerList

### ISSUE THREAD

**Issue by bitchkat** [shayhatsor/zookeeper#22]
I'm working on porting Apache Curator to .Net and it makes a call to ZooKeeper.updateServerList(String)

Any chance we can get that added to your ZooKeeper class?

**Comment by shayhatsor** [comment]
This is one of those rare chunks of code that I didn't port from java. I'll see how I can port it, the only problem is that it changes the server list on a running ZK client, which will probably cause race conditions.

**Comment by bitchkat** [comment]
Thanks.  For the record, I ended running modifying this chunk of code to use reflection to only invoke the method if it exists.
