### ISSUE TITLE
Why watcher cannot be null?

### ISSUE THREAD

**Issue by 8089wang** [shayhatsor/zookeeper#24]
It will be thrown null pointer exception when watcher is null in Zookeeper.cs line 396. if watcher can be null it is more stable.

Also see follow code:

 public ZooKeeper(string connectString, int sessionTimeout, Watcher watcher,
            long sessionId, byte[] sessionPasswd, bool canBeReadOnly = false) {
            LOG.info("Initiating client connection, connectString=" + connectString
                     + " sessionTimeout=" + sessionTimeout
                     + " watcher=" + watcher
                     + " sessionId=" + sessionId.ToHexString()
                     + " sessionPasswd="
                     + (sessionPasswd == null ? "<null>" : "<hidden>"));

            sessionPasswd = sessionPasswd ?? NO_PASSWORD;
            watchManager.defaultWatcher = new WatcherDelegate(@event =>
            {
                if (@event.getState() == Watcher.Event.KeeperState.SyncConnected || @event.getState() == Watcher.Event.KeeperState.ConnectedReadOnly) 
                { 
                    connectedSignal.Set();
                }
                else
                { 
                    if(connectedSignal.Task.IsCompleted) connectedSignal.Reset();
                }   
                

                        return watcher.process(@event);

            });

**Comment by shayhatsor** [comment]
null pointer exception is also thrown in this case by the java client, i kept the same behaviour
