### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by nj4x** [shayhatsor/zookeeper#3]
Hit this exception when using WriteLock without LockListener callback:

Location: org.apache.zookeeper.recipes.lock.WriteLock.LockZooKeeperOperation

Reason: writeLock.callback is null

```
                                lock (writeLock.callback) {
                                    if (writeLock.callback != null) {
                                        writeLock.callback.lockAcquired();
                                    }
                                }
```

**Comment by shayhatsor** [comment]
nice catch, the recipes library is much less mature then the main zookeeper one. my tests are imported from java, i guess this scenario wasn't covered as it is a bug introduced by me.
i've made a fix and released a new nuget. (3.4.7.3)

**Comment by nj4x** [comment]
Great! Thank you, Shay.
