### ISSUE TITLE
addListener will never called, DispatchEvent will never been called

### ISSUE THREAD

**Issue by Elvin1492** [shayhatsor/zookeeper#31]
if I understood well there is not any caller of addlistener in LeaderElectionSupport. Also, the dummy variable is always empty. 

So how should we use addListeners?

**Comment by shayhatsor** [comment]
for examples on how to use the leader election recipe i suggest looking at [the tests](https://github.com/shayhatsor/zookeeper/blob/trunk/src/csharp/test/ZooKeeperNetEx.Recipes.Tests/leader/LeaderElectionSupportTest.cs)
