### ISSUE TITLE
3.5.* Nuget

### ISSUE THREAD

**Issue by karlomedallo** [shayhatsor/zookeeper#32]
Hi,
Do you know when 3.5.x releases be in nuget? Also, can the RC releases be a prerelease version too?

Thanks!

**Comment by karlomedallo** [comment]
We encountered a similar issue described here (without the high memory usage) https://github.com/shayhatsor/zookeeper/issues/25 and we would like to use the 3.5.x release (we are on 3.4.10.1, comes with SolrNet)

Also, with symptoms described in the issue above, is there an easy way to look at our zk logs (or any other logs) and see if it was likely caused by that bug? TIA

**Comment by shayhatsor** [comment]
about 3.5.x releases, they are prereleases. i have decided to keep up with the stable release versions, as those are the ones that most people use.
about #25, the bug is resolved in master. i'm planning to release it with some performance improvements in the near future.

**Comment by karlomedallo** [comment]
Thanks @shayhatsor ! hopefully your nuget account issue gets resolved soon. waiting for the release

**Comment by shayhatsor** [comment]
np, my nuget account issues were finally resolved after several days (of stress 😄).

**Comment by lkaszick** [comment]
Hi @shayhatsor great to hear your nuget issue was resolved! Do you have any estimate for when version 3.5 might be released?

**Comment by shayhatsor** [comment]
Are you asking when the Apache Zookeeper 3.5 will be released ? I have no idea, I am not affiliated with Apache in any way. This is a project I work on in my spare time.

**Comment by lkaszick** [comment]
I mean the release of your zookeeper port. Specifically with the patch for the high CPU mentioned in bug https://github.com/shayhatsor/zookeeper/issues/25

You mentioned you're "planning to release it with some performance improvements in the near future", do you have an ETA for that release?

**Comment by shayhatsor** [comment]
now, actually :)
