### ISSUE TITLE
Example request: Connecting to a secured Zookeeper

### ISSUE THREAD

**Issue by manchuwook** [shayhatsor/zookeeper#36]
How would I connect to a secured instance of Zookeeper using this library?  Would it just know which directory has the correct SSL certs?

**Comment by shayhatsor** [comment]
Unfortunately, when i ported the code from JAVA I didn't implement the SASL layer.

**Comment by manchuwook** [comment]
It's hard to find a library that does implement SASL. :C

**Comment by shayhatsor** [comment]
if you're interested in securing the transport between ZooKeeper clients and servers, you can use nginx to SSL encrypt the tcp stream: https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-upstreams/. this requires having nginx installed in both clients and servers, i've been using this method in production and it works great. if you're interested in an example config, i can paste something here.
