### ISSUE TITLE
.Net code is not compilable due to missing files in source code folders

### ISSUE THREAD

**Issue by prempyadav** [shayhatsor/zookeeper#41]
Please upload compilable complete code on git. Dlls are working fine but need to lib debug code for some issues

![Compilation Errors](https://user-images.githubusercontent.com/12065577/70996019-e806eb80-20f7-11ea-8ea5-2487fb7a50a0.png)
![Compilation Errors](https://user-images.githubusercontent.com/12065577/70996039-f5bc7100-20f7-11ea-996c-bf1e0ccdf249.png)

.

**Comment by shayhatsor** [comment]
have you read the readme file ?
