### ISSUE TITLE
WriteLock.close() does not release the lock acquired

### ISSUE THREAD

**Issue by nj4x** [shayhatsor/zookeeper#6]
I understand that it is not a part of java implementation, but is it correct that method with such description:

```
    Closes this strategy and releases any ZooKeeper resources; but keeps the ZooKeeper instance open 
```

does not release the lock?

**Comment by shayhatsor** [comment]
@nj4x, I have removed the method altogether. The new version is available from nuget.

**Comment by nj4x** [comment]
thanks!
