### ISSUE TITLE
Public accessability for KeeperException, KeeperException.Code

### ISSUE THREAD

**Issue by Lagrang** [shayhatsor/zookeeper#9]
I try to create port of Curator library.
Java code of Curator library actively use KeeperException(and it's subtypes) and KeeperException.Code. But in your library this types have very restricted access. 
Can you change accessability modifiers to public for constructors of KeeperException(and it's subtypes) and also make public KeeperException.Code enum? This can help me:)

**Comment by shayhatsor** [comment]
I'll roll out a new version with your required changes within the next few days.
It's great that you're porting the Curator library, I started to do it some time ago but never got around to finish it. If you look at my curator fork, you might find it to be a good starting point. Have fun :)

**Comment by Lagrang** [comment]
Thanks that you accept my changes! I'm very happy
I understand why you don't finish it, it's very time consuming and hard work:)

**Comment by shayhatsor** [comment]
@Lagrang, would you mind submitting a PR with your desired changes? I was to make sure I include all your required changes. thanks :)

**Comment by Lagrang** [comment]
@shayhatsor, yes,sure:)
Add pull request #10

**Comment by shayhatsor** [comment]
@Lagrang, thanks for the PR, I've rolled out a new version 3.4.8.4 with your commit included.
